

url = '/investigacion/part_eventos_academicos'
data = {
'bool_eventos_academicos': 'si',

'titulo_1' : 'este es titulo _1',
'evento_1' : 'este es evento _1',
'lugar_1' : 'este es lugar _1',
'fecha_1' : '2024-12-10',
'tipo_participacion_1' : 'tipo_participacion_1',
'modalidad_1' : 'virtual',
'aprobado_1': 'si',
'path_file_1': 'path_file_1',
'bool_semillero_1': 'si',
'semillero_1': 'el semillero',
'estudiante_1_1': 'pepi_1_1',
'estudiante_1_2': 'pepi_1_2',
'estudiante_1_3': 'pepi_1_3',
'estudiante_1_4': 'pepi_1_4',
'estudiante_1_5': 'pepi_1_5',
'estudiante_1_6': 'pepi_1_6',
'estudiante_1_7': 'pepi_1_7',
'estudiante_1_8': 'pepi_1_8',
'movilidad_1': 'internacional',

'titulo_2' : 'este es titulo _2',
'evento_2' : 'este es evento _2',
'lugar_2' : 'este es lugar _2',
'fecha_2' : '2024-12-10',
'tipo_participacion_2' : 'tipo_participacion_2',
'modalidad_2' : 'virtual',
'aprobado_2': 'no',
'path_file_2': 'path_file_2',
'bool_semillero_2': 'no',
'semillero_2': 'el semillero',
'estudiante_2_1': 'pepi_2_1',
'estudiante_2_2': 'pepi_2_2',
'estudiante_2_3': 'pepi_2_3',
'estudiante_2_4': 'pepi_2_4',
'estudiante_2_5': 'pepi_2_5',
'estudiante_2_6': 'pepi_2_6',
'estudiante_2_7': 'pepi_2_7',
'estudiante_2_8': 'pepi_2_8',
'movilidad_2': 'nacional',

'titulo_10' : 'este es titulo _10',
'evento_10' : 'este es evento _10',
'lugar_10' : 'este es lugar _10',
'fecha_10' : '2024-12-10',
'tipo_participacion_10' : 'tipo_participacion_10',
'modalidad_10' : 'presencial',
'aprobado_10': 'si',
'path_file_10': 'path_file_10',
'bool_semillero_10': 'no',
'movilidad_10': 'regional',
'semillero_10': '',
'estudiante_10_1': '',
'period_spam': '2024-2'
}

datafail = {
'bool_eventos_academicos': 'si',

'titulo_1' : 'este es titulo _1',
'evento_1' : 'este es evento _1',
'lugar_1' : 'este es lugar _1',
'fecha_1' : '2024-12-1s0',
'tipo_participacion_1' : 'tipo_participacion_1',
'modalidad_1' : 'virtal',
'aprobado_1': 'si',
'path_file_1': 'path_file_1',
'bool_semillero_1': 's',
'semillero_1': 'el semillero',
'estudiante_1_1': 'pepi_1_1',
'estudiante_1_2': 'pepi_1_2',
'estudiante_1_3': 'pepi_1_3',
'estudiante_1_4': 'pepi_1_4',
'estudiante_1_5': 'pepi_1_5',
'estudiante_1_6': 'pepi_1_6',
'estudiante_1_7': 'pepi_1_7',
'estudiante_1_8': 'pepi_1_8',
'movilidad_1': 'internacional',

'titulo_2' : 'este es titulo _2',
'evento_2' : 'este es evento _2',
'lugar_2' : 'este es lugar _2',
'fecha_2' : '2024-12-10',
'tipo_participacion_2' : 'tipo_participacion_2',
'modalidad_2' : 'virtual',
'aprobado_2': 'n',
'path_file_2': 'path_file_2',
'bool_semillero_2': 'no',
'semillero_2': 'el semillero',
'estudiante_2_1': 'pepi_2_1',
'estudiante_2_2': 'pepi_2_2',
'estudiante_2_3': 'pepi_2_3',
'estudiante_2_4': 'pepi_2_4',
'estudiante_2_5': 'pepi_2_5',
'estudiante_2_6': 'pepi_2_6',
'estudiante_2_7': 'pepi_2_7',
'estudiante_2_8': 'pepi_2_8',
'movilidad_2': 'nacional',

'titulo_10' : 'este es titulo _10',
'evento_10' : 'este es evento _10',
'lugar_10' : 'este es lugar _10',
'fecha_10' : '2024-12-10',
'tipo_participacion_10' : 'tipo_participacion_10',
'modalidad_10' : 'presncial',
'aprobado_10': 'si',
'path_file_10': 'path_file_10',
'bool_semillero_10': 'no',
'movilidad_10': 'regial',
'semillero_10': '',
'estudiante_10_1': '',
'period_spam': '2024-2'
}
respuesta_espeda = '''El formato de fecha no es valido
virtal no es un valor valido
presncial no es un valor valido
regial no es un valor valido
'''

