

url = '/investigacion/desarollo_proyectos_investigacion_creacion'
data = {
'bool_proyectos': 'si',
'nombre_proyecto_1' : 'nombre1',
'code_1': 'code1',
'tipo_convocatoria_1': 'interna',
'nombre_convocatoria_1': 'nombreCon1',
'elegido_1': 'si',
'financiamiento_1': '',
'tipo_participacion_1': 'principal',
'bool_semillero_1': 'si',
'semillero_1': 'el semillero',
'estudiante_1_1': 'pepi_1_1',
'estudiante_1_2': 'pepi_1_2',
'estudiante_1_3': 'pepi_1_3',
'estudiante_1_4': 'pepi_1_4',
'estudiante_1_5': 'pepi_1_5',
'estudiante_1_6': 'pepi_1_6',
'estudiante_1_7': 'pepi_1_7',
'estudiante_1_8': 'pepi_1_8',
'ods_1': 'si',
'software_1': 'si',
'idi5_1': 'no',

'nombre_proyecto_2' : 'nombre1',
'code_2': 'code1',
'tipo_convocatoria_2': 'interna',
'nombre_convocatoria_2': 'nombreCon1',
'elegido_2': 'si',
'financiamiento_2': '',
'tipo_participacion_2': 'co_investigador',
'bool_semillero_2': 'si',
'semillero_2': 'el semillero',
'estudiante_2_1': 'pepi_2_1',
'estudiante_2_2': 'pepi_2_2',
'estudiante_2_3': 'pepi_2_3',
'estudiante_2_4': 'pepi_2_4',
'estudiante_2_5': 'pepi_2_5',
'estudiante_2_6': 'pepi_2_6',
'estudiante_2_7': 'pepi_2_7',
'estudiante_2_8': 'pepi_2_8',
'ods_2': 'si',
'software_2': 'si',
'idi5_2': 'no',

'nombre_proyecto_3' : 'nombre1',
'code_3': 'code1',
'tipo_convocatoria_3': 'interna',
'nombre_convocatoria_3': 'nombreCon1',
'elegido_3': 'si',
'financiamiento_3': '',
'tipo_participacion_3': 'principal',
'bool_semillero_3': 'no',
'semillero_3': 'el semillero',
'estudiante_3_1': 'pepi_3_1',
'estudiante_3_2': 'pepi_3_2',
'estudiante_3_3': 'pepi_3_3',
'estudiante_3_4': 'pepi_3_4',
'estudiante_3_5': 'pepi_3_5',
'estudiante_3_6': 'pepi_3_6',
'estudiante_3_7': 'pepi_3_7',
'estudiante_3_8': 'pepi_3_8',
'ods_3': 'no',
'software_3': 'si',
'idi5_3': 'si',

'period_spam': '2024-2'
}

datafail = {
'bool_proyectos': 'si',
'nombre_proyecto_1' : 'nombre1',
'code_1': 'code1',
'tipo_convocatoria_1': 'interna',
'nombre_convocatoria_1': 'nombreCon1',
'elegido_1': 'si',
'financiamiento_1': '',
'tipo_participacion_1': 'principal',
'bool_semillero_1': 'si',
'semillero_1': '',
'estudiante_1_1': 'pepi_1_1',
'estudiante_1_2': 'pepi_1_2',
'estudiante_1_3': 'pepi_1_3',
'estudiante_1_4': 'pepi_1_4',
'estudiante_1_5': 'pepi_1_5',
'estudiante_1_6': 'pepi_1_6',
'estudiante_1_7': 'pepi_1_7',
'estudiante_1_8': 'pepi_1_8',
'ods_1': 'si',
'software_1': 'si',
'idi5_1': 'no',

'nombre_proyecto_2' : 'nombre1',
'code_2': 'code1',
'tipo_convocatoria_2': 'internal',
'nombre_convocatoria_2': 'nombreCon1',
'elegido_2': 'si',
'financiamiento_2': '',
'tipo_participacion_2': 'co_investigador',
'bool_semillero_2': 'si',
'semillero_2': 'el semillero',
'estudiante_2_1': 'pepi_2_1',
'estudiante_2_2': 'pepi_2_2',
'estudiante_2_3': 'pepi_2_3',
'estudiante_2_4': 'pepi_2_4',
'estudiante_2_5': 'pepi_2_5',
'estudiante_2_6': 'pepi_2_6',
'estudiante_2_7': 'pepi_2_7',
'estudiante_2_8': 'pepi_2_8',
'ods_2': 'si',
'software_2': 'si',
'idi5_2': 'no',

'nombre_proyecto_3' : 'nombre1',
'code_3': 'code1',
'tipo_convocatoria_3': 'interna',
'nombre_convocatoria_3': 'nombreCon1',
'elegido_3': 'si',
'financiamiento_3': '',
'tipo_participacion_3': 'ww',
'bool_semillero_3': 'no',
'semillero_3': 'el semillero',
'estudiante_3_1': 'pepi_3_1',
'estudiante_3_2': 'pepi_3_2',
'estudiante_3_3': 'pepi_3_3',
'estudiante_3_4': 'pepi_3_4',
'estudiante_3_5': 'pepi_3_5',
'estudiante_3_6': 'pepi_3_6',
'estudiante_3_7': 'pepi_3_7',
'estudiante_3_8': 'pepi_3_8',
'ods_3': 'no',
'software_3': 'si',
'idi5_3': 'si',

'period_spam': '2024-2'
}

respuesta_espeda = '''falta indicar el nombre del semillero
internal no es un valor valido
ww no es un valor valido
'''

